SRC_NAME = V2RayA
THISDIR = $(shell pwd)

all:

extract_test:

config_test:
clean:

romfs:
	$(ROMFSINST) $(THISDIR)/v2raya.sh /usr/bin/v2raya.sh
	$(ROMFSINST) $(THISDIR)/v2raya_linux_mips32le_2.2.6.7 /usr/bin/v2raya

